apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopeasy
  template:
    metadata:
      labels:
        app: shopeasy
    spec:
      containers:
        - name: shopeasy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
            - containerPort: 5000

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: shopeasy-config
                  key: APP_NAME

          volumeMounts:
            - name: temp-storage
              mountPath: /tmp/cache

            - name: persistent-storage
              mountPath: /app/uploads

      volumes:
        - name: temp-storage
          emptyDir: {}

        - name: persistent-storage
          persistentVolumeClaim:
            claimName: shopeasy-pvc